### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by oserban** [ove/ove-install#14]
This task has to test the stability of the whole OVE ecosystem, including:
- OVE
- OVE Apps
- OVE Layout Service
- Tuoris as a service

If the tests are successful, travis needs to retag the components from latest-unstable to latest

**Comment by oserban** [comment]
This has been done by the server check tool

**Comment by jamesscottbrown** [comment]
This isn't really satisfactory, because the gdo-server-check tool is in a private repository.

The integration test should be runnable by *anyone* who has used the OVE installer, and there should ideally be an option to install and run this tool when the installer is run.

**Comment by oserban** [comment]
This is one of those things that have been open for a while and nobody will do because it doesn't excite anybody. On the other hand, I realised a while ago that integration testing is site dependent, we would not be able to create a tool that covers everything. These days most people use other projects for monitoring, so this is useless for most users.
