### ISSUE TITLE
Update docker hub description for all projects

### ISSUE THREAD

**Issue by oserban** [ove/ove-install#18]

**Comment by senakafdo** [comment]
This has been fixed for OVE and OVE apps projects that have been properly released on GitHub and DockerHub. This can be done for all other projects when they are fully released on both GitHub and DockerHub. 

Some projects are only partially released, such as the Tuoris external service. We need to find a way of properly releasing that on GitHub for us to be able to achieve this. @oserban FTR.

I am resolving this issue as there is nothing further to be done here. The task would be down to the respective release manager(s) to implement when they make their releases.
