### ISSUE TITLE
Docker compose incorrectly specifies http:// for hosts

### ISSUE THREAD

**Issue by DavidAkroyd** [ove/ove-install#20]
Docker compose file incorrectly prompts users to add hostname with http://

This is incorrect - the http:// is prepended by OVE, so this results in `http://http://hostname`

```
environment:
      OVE_HOST: "http://public-hostname-or-ip:8080"
      TUORIS_HOST: "http://public-hostname-or-ip:7080"
```

**Comment by senakafdo** [comment]
Fixed in af533d6.
