### ISSUE TITLE
Update builds to include OpenVidu dependencies

### ISSUE THREAD

**Issue by jamesscottbrown** [ove/ove-install#26]
The webrtc app requires two extra variables, `OPENVIDU_HOST` and `OPENVIDU_SECRET`.
Without these, it will give an error, and the whole over-apps Docker image will fail to start.

**Comment by senakafdo** [comment]
We also need to include the OpenVidu dependencies such as Kurento (along with environment variables it expects) into our build, or else it will still not work.
