### ISSUE TITLE
MacOS support testing

### ISSUE THREAD

**Issue by oserban** [ove/ove-install#6]
- [x] Multistage builds, e.g. asset manager
- [x] Build script, e.g. build.sh

**Comment by senakafdo** [comment]
Confirmed that ./build.sh scripts work on Mac. Will be able to test the multi-stage builds within ove-install once ove/ove-asset-services#24 is resolved.

**Comment by senakafdo** [comment]
Tested multi-stage build for the asset manager as well, and it works well.
