### ISSUE TITLE
Other Linux testing support & supported distro page

### ISSUE THREAD

**Issue by oserban** [ove/ove-install#7]
- [ ] Multistage builds, e.g. asset manager
- [ ] Build script, e.g. build.sh
- [ ] Docker deployment test
- [ ] Bare metal deployment test

The Readme file should be updated with the results of this testing session

**Comment by senakafdo** [comment]
Proper thing to do would be to define a solid integration test case(s) for OVE and then build it and run it on various operating systems using an online build service, because, tested once doesn't mean this will stay put forever.
